package provider

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/parnurzeal/gorequest"
	"github.com/sirupsen/logrus"
)

const (
	urlWolfram = "http://api.wolframalpha.com/v2/query?appid=%s&input=%s&output=JSON&format=image,plaintext"
)

type (
	Wolfram interface {
		Ask(string) (*WolframResponse, error)
	}

	wolfram struct {
		token string
	}

	WolframResponse struct {
		Queryresult struct {
			Success       bool    `json:"success"`
			Error         bool    `json:"error"`
			Pods          []struct {
				Title string `json:"title"`
				Subpods    []struct {
					Title string `json:"title"`
					Plaintext string `json:"plaintext"`
				} `json:"subpods"`
			} `json:"pods"`
		} `json:"queryresult"`
	}
)
type AutoGenerated struct {
	Queryresult struct {
		Success       bool    `json:"success"`
		Error         bool    `json:"error"`
		Numpods       int     `json:"numpods"`
		Datatypes     string  `json:"datatypes"`
		Timedout      string  `json:"timedout"`
		Timedoutpods  string  `json:"timedoutpods"`
		Timing        float64 `json:"timing"`
		Parsetiming   float64 `json:"parsetiming"`
		Parsetimedout bool    `json:"parsetimedout"`
		Recalculate   string  `json:"recalculate"`
		ID            string  `json:"id"`
		Host          string  `json:"host"`
		Server        string  `json:"server"`
		Related       string  `json:"related"`
		Version       string  `json:"version"`
		Didyoumeans   []struct {
			Score string `json:"score"`
			Level string `json:"level"`
			Val   string `json:"val"`
		} `json:"didyoumeans"`
	} `json:"queryresult"`
}

func NewWolfram(token string) Wolfram {
	return &wolfram{
		token: token,
	}
}

//Ask returns weather by City name.
func (w *wolfram) Ask(question string) (*WolframResponse, error) {
	body, err := w.makeRequest(question)
	if err != nil {
		return nil, err
	}

	return w.transformStringToResponse(body)
}

func (w *wolfram) makeRequest(question string) (body string, err error) {
	url := fmt.Sprintf(urlWolfram, w.token, question)
	logrus.Infof("Making Request: %s", url)
	_, body, errs := gorequest.New().Get(url).End()
	if errs != nil {
		return "", errs[0]
	}

	return body, nil
}

func (w *wolfram) transformStringToResponse(body string) (*WolframResponse, error) {
	resp := WolframResponse{}
	fmt.Println(body)
	if err := json.Unmarshal([]byte(body), &resp); err != nil {
		return nil, err
	}

	if resp.Queryresult.Error || !resp.Queryresult.Success {
		return nil, errors.New("error in the question")
	}

	return &resp, nil
}
